kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  labels:
    name: pod-1
    purpose: pod-affinity
spec:
  containers:
  - name: pod-1
    image: nginx
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-2
  labels:
    name: pod-2
    purpose: pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: pod-2
    image: nginx

# apiVersion: v1
# kind: Pod
# metadata:
#   name: pod-affinity
# spec:
#   affinity:
#     podAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchExpressions:
#           - key: security
#             operator: In
#             values:
#             - S1
#         topologyKey: topology.kubernetes.io/zone
#     podAntiAffinity:
#       preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 100
#         podAffinityTerm:
#           labelSelector:
#             matchExpressions:
#             - key: security
#               operator: In
#               values:
#               - S2
#           topologyKey: topology.kubernetes.io/zone
#   containers:
#   - name: with-pod-affinity
#     image: registry.k8s.io/pause:3.8
