apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f41
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static-claim
---
kind: Pod
apiVersion: v1
metadata: 
  name: pod-np
spec:
  type: NodePort
  selector:
    purpose: ebs-static
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #target port
      nodePort: 31123 #we can fix the node port like this