# kind: Namespace
# apiVersion: v1
# metadata:
#   name: expense
#   labels:
#     name: expense
#     environment: dev
    

# kind: Namespace
# apiVersion: v1
# metadata:
#   name: expense
#   labels:
#     name: expense
#     environment: dev



kind: Namespace
apiVersion: v1
metadata:
  name: ecc
  labels:
    name: exx
    environment: dev

