kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: sets
  labels:
    name: backend
    project: expense
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx