# kind: Pod
# apiVersion: v1
# metadata:
#   name: con-map
# data:
#   course: "aws cloud k8s"
#   trainer: 'me'
#   github: "https://github.com/jeethvishnu/mykubernetes.git"

kind: ConfigMap
apiVersion: v1
metadata:
  name: configs
  labels:
    purpose: dev
data:
  course: "aws cloud k8s"
  trainer: 'me'
  github: "https://github.com/jeethvishnu/mykubernetes.git"



      
