kind: Pod
apiVersion: v1
metadata: 
  name: refer-pod
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: configs
# kind: Pod
# apiVersion: v1
# metadata:
#   name: configaring
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     envFrom:
#     - configMapRef:
#       name: con-map
#       # 2nd way
    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: con-map
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: con-map
    #       key: trainer
