apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always #keep this always
  tolerations:
  - key: "" #give key
    # operator: "Exists" #these are the different operators refer k8 docs
    operator: "Equal"
    value: "" #give your value
    effect: "NoSchedule" #give your effect
  tolerations:
  - key: "key1"
    operator: "Exists"
    effect: "NoSchedule"


# this will only work if the labels are matched