apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: "" #give your key here first you need to set the labels to the node and 
                      # we need to make sure that this pod should run in that node.
              operator: In
              values:
                ""
  containers:
  - name: with-node-affinity
    image: nginx 