apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1
    purpose: podaffinity
spec:
  containers:
  - name: pod-1
    image: nginx
    imagePullPolicy: Always 
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: pod-1
    purpose: podaffinity 
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: pod-2
    image: nginx
    imagePullPolicy: Always 