kind: Deployment
apiVersion: apps/v1
metadata: 
  name: ingress
  labels:
    component: backend
    project: expense
spec:
  selector:
    matchLabels:
      purpose: ingress
      project: app1
  template:
    metadata:
      labels:
        purpose: ingress
        project: app1
    spec:
      containers:
      - name: nginx
        image: jeeth22/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: pod-np
spec:
  selector:
    purpose: ingress
    project: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
